name: learnforge_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_animate: ^4.5.2
  lottie: ^3.3.1
  uuid: ^4.5.2
  flutter_riverpod: ^2.4.9
  go_router: ^16.3.0
  intl: ^0.20.2
  hive_flutter: ^1.1.0
  video_player: ^2.8.2
  youtube_player_flutter: ^9.1.3
  youtube_player_iframe: ^5.2.2
  flutter_inappwebview: ^6.1.5  # Updated to latest stable version
  font_awesome_flutter: ^10.9.1
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/avatar_default.png
    - assets/images/icon.png
    - assets/images/icon-removebg-preview.png
    - assets/lottie/
    - assets/animations/

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/orbitron/Orbitron-VariableFont_wght.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/inter/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
